# Generated by Django 4.0.5 on 2022-06-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0002_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='title', max_length=100)),
                ('description', models.TextField(db_column='description', max_length=1000)),
                ('photo1', models.BinaryField(blank=True, db_column='photo1', editable=True, null=True)),
                ('photo2', models.BinaryField(blank=True, db_column='photo2', editable=True, null=True)),
                ('photo3', models.BinaryField(blank=True, db_column='photo3', editable=True, null=True)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'db_table': 'post',
            },
        ),
    ]
