# Generated by Django 4.0.5 on 2022-06-10 11:24

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0005_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='title', max_length=100)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Publicoffer',
                'verbose_name_plural': 'Publicoffers',
                'db_table': 'publicoffer',
            },
        ),
    ]
