# Generated by Django 4.0.5 on 2022-06-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0006_publicoffer'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, db_column='link', max_length=100)),
                ('photo', models.BinaryField(blank=True, db_column='photo', editable=True, null=True)),
            ],
            options={
                'verbose_name': 'Main page',
                'verbose_name_plural': 'Main pages',
                'db_table': 'mainpage',
            },
        ),
    ]
