# Generated by Django 4.0.5 on 2022-06-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0007_mainpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefit',
            name='icon',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='photo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
