# Generated by Django 4.0.5 on 2022-06-13 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0008_alter_benefit_icon_alter_collection_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefit',
            name='icon',
            field=models.BinaryField(blank=True, db_column='icon', editable=True, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='photo',
            field=models.BinaryField(blank=True, db_column='photo', editable=True, null=True),
        ),
    ]
