# Generated by Django 4.0.5 on 2022-06-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0014_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='col',
            field=models.CharField(choices=[('green', 'green'), ('red', 'red')], max_length=256, null=True),
        ),
    ]
