# Generated by Django 4.0.5 on 2022-06-14 08:03

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0017_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='photo',
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.IntegerField(blank=True, db_column='discount', default=100),
        ),
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.IntegerField(blank=True, db_column='old_price', default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, db_column='price', default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(blank=True, db_column='title', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='item',
            field=models.CharField(blank=True, db_column='item', max_length=100),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None),
        ),
    ]
