# Generated by Django 4.0.5 on 2022-06-14 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0018_remove_product_photo_product_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='item',
        ),
    ]
