# Generated by Django 4.0.5 on 2022-06-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0019_remove_product_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='title',
        ),
        migrations.AddField(
            model_name='product',
            name='item',
            field=models.CharField(blank=True, db_column='item', max_length=100),
        ),
    ]
