# Generated by Django 4.0.5 on 2022-06-14 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0020_remove_product_title_product_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='item',
        ),
    ]
