# Generated by Django 4.0.5 on 2022-06-14 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0021_remove_product_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
