# Generated by Django 4.0.5 on 2022-06-14 08:18

import ckeditor.fields
import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0022_remove_productimage_product_delete_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, db_column='item', max_length=100)),
                ('title', models.CharField(blank=True, db_column='title', max_length=100)),
                ('collection', models.CharField(choices=[], max_length=256, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, db_column='price', default=0)),
                ('discount', models.IntegerField(blank=True, db_column='discount', default=100)),
                ('old_price', models.IntegerField(blank=True, db_column='old_price', default=0)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storeapp.product')),
            ],
            options={
                'verbose_name': 'ProductImage',
                'verbose_name_plural': 'ProductImage',
                'db_table': 'productimage',
            },
        ),
    ]
