# Generated by Django 4.0.5 on 2022-06-14 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0023_product_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='item',
        ),
    ]
