# Generated by Django 4.0.5 on 2022-06-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0025_alter_product_discount_alter_product_old_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, db_column='size', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='size_count',
            field=models.IntegerField(blank=True, db_column='size_count', default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='collection',
            field=models.CharField(blank=True, choices=[], max_length=256, null=True),
        ),
    ]
