# Generated by Django 4.0.5 on 2022-06-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0027_product_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hits',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='novelty',
            field=models.BooleanField(default=False),
        ),
    ]
