# Generated by Django 4.0.5 on 2022-06-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0029_product_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fabric',
            field=models.CharField(blank=True, db_column='fabric', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='fabric_composition',
            field=models.CharField(blank=True, db_column='fabric_composition', max_length=100),
        ),
    ]
