# Generated by Django 4.0.5 on 2022-06-14 10:47

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0030_product_fabric_product_fabric_composition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='color',
            field=colorfield.fields.ColorField(db_column='color', default='#FFFFFF', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='storeapp.product'),
        ),
    ]
