# Generated by Django 4.0.5 on 2022-06-14 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0031_alter_productimage_color_alter_productimage_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
