# Generated by Django 4.0.5 on 2022-06-14 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0033_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='collection',
            field=models.ForeignKey(default='New', on_delete=django.db.models.deletion.CASCADE, related_name='colleciton_list', to='storeapp.collection'),
        ),
    ]
