# Generated by Django 4.0.5 on 2022-06-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0034_alter_product_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='collection',
            field=models.CharField(blank=True, choices=[('Summer-2022', 'Summer-2022'), ('Winter-2022', 'Winter-2022')], max_length=256, null=True),
        ),
    ]
