# Generated by Django 4.0.5 on 2022-06-14 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0037_alter_product_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='item',
        ),
    ]
