# Generated by Django 4.0.5 on 2022-06-15 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0039_product_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
