# Generated by Django 4.0.5 on 2022-06-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0042_help_helpimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_column='name', max_length=100)),
                ('number', models.CharField(blank=True, db_column='number', max_length=100)),
                ('call_type', models.CharField(blank=True, db_column='call_type', max_length=100)),
            ],
            options={
                'verbose_name': 'Call',
                'verbose_name_plural': 'Calls',
                'db_table': 'call',
            },
        ),
    ]
