# Generated by Django 4.0.5 on 2022-06-20 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0044_call_call_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='call_status',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=256, null=True),
        ),
    ]
