# Generated by Django 4.0.5 on 2022-06-21 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0046_footer_alter_post_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footer',
            old_name='phone_number',
            new_name='header_number',
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_type', models.CharField(choices=[('Telegram', 'Telegram'), ('Whatsapp', 'Whatsapp')], max_length=256, null=True)),
                ('contact', models.CharField(db_column='contact', max_length=100)),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='storeapp.footer')),
            ],
            options={
                'verbose_name': 'ContactInfo',
                'verbose_name_plural': 'ContactInfo',
                'db_table': 'contactinfo',
            },
        ),
    ]
