# Generated by Django 4.0.5 on 2022-06-22 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0047_rename_phone_number_footer_header_number_contactinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benefit',
            options={'verbose_name': 'Benefit', 'verbose_name_plural': 'Наши преимущества'},
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='network_type',
            field=models.CharField(choices=[('Telegram', 'Telegram'), ('Whatsapp', 'Whatsapp'), ('Instagram', 'Instagram'), ('Mail', 'Mail'), ('Phone', 'Phone')], max_length=256, null=True),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(db_column='text', max_length=100)),
                ('product', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storeapp.product')),
            ],
        ),
    ]
