# Generated by Django 4.0.5 on 2022-06-22 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0048_alter_benefit_options_alter_contactinfo_network_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='color',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storeapp.productimage'),
        ),
    ]
