# Generated by Django 4.0.5 on 2022-06-24 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0051_order_remove_orderitem_color_remove_orderitem_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='order',
        ),
    ]
