# Generated by Django 4.0.5 on 2022-06-24 12:08

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0055_shippingaddress_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(db_column='text', max_length=100)),
                ('color', colorfield.fields.ColorField(db_column='color', default='#FFFFFF', image_field=None, max_length=18, samples=None)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('product', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storeapp.product')),
            ],
        ),
    ]
