# Generated by Django 4.0.5 on 2022-06-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0057_alter_cartitem_order_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.IntegerField(blank=True, db_column='total', default=0),
        ),
    ]
