# Generated by Django 4.0.5 on 2022-06-27 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0058_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='final_price',
            field=models.IntegerField(blank=True, db_column='final_price', default=0),
        ),
    ]
