# Generated by Django 4.0.5 on 2022-06-28 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0059_order_final_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='order_hist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_hist', to='storeapp.order'),
        ),
    ]
