# Generated by Django 4.0.5 on 2022-06-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0062_remove_cartitem_date_added_remove_order_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='price',
            field=models.IntegerField(blank=True, db_column='final_price', default=0),
        ),
    ]
