# Generated by Django 4.0.5 on 2022-06-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0064_shippingaddress_email_shippingaddress_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products_count',
            field=models.IntegerField(blank=True, db_column='products_count', default=0),
        ),
    ]
