# Generated by Django 4.0.5 on 2022-06-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0065_order_products_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items_count',
            field=models.IntegerField(blank=True, db_column='items_count', default=0),
        ),
    ]
